"""Add account_number column

Revision ID: f5690cf1cddd
Revises: 
Create Date: 2025-05-07 14:06:21.349193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5690cf1cddd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_number', sa.BigInteger(), nullable=False))
        batch_op.create_unique_constraint(None, ['account_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('account_number')

    # ### end Alembic commands ###
